name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x

      - name: Install dependencies
        run: make install

      - name: Run Rubocop
        run: make lint

      - name: Run tests
        run: make test
